#!/bin/bash
#
# PlexMCP Self-Hosting Setup Script
#
# This script helps you set up PlexMCP for self-hosting by:
# 1. Generating secure secrets
# 2. Creating the .env file
# 3. Validating the configuration
#
# Usage: ./scripts/setup.sh

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print with color
print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Header
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                 PlexMCP Self-Hosting Setup                   ║"
echo "║                                                              ║"
echo "║  This script will help you configure PlexMCP for            ║"
echo "║  self-hosting by generating secure secrets and creating     ║"
echo "║  your environment configuration.                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Check for required tools
print_info "Checking for required tools..."

MISSING_TOOLS=0

if ! command -v openssl &> /dev/null; then
    print_error "openssl is required but not installed."
    print_info "Install it with: brew install openssl (macOS) or apt install openssl (Linux)"
    MISSING_TOOLS=1
fi

if ! command -v docker &> /dev/null; then
    print_error "Docker is required but not installed."
    print_info "Install it from: https://docs.docker.com/get-docker/"
    MISSING_TOOLS=1
fi

if ! command -v docker compose &> /dev/null && ! docker compose version &> /dev/null; then
    print_error "Docker Compose is required but not installed."
    print_info "It should be included with Docker Desktop, or install the plugin."
    MISSING_TOOLS=1
fi

if [ $MISSING_TOOLS -eq 1 ]; then
    print_error "Please install missing tools and run this script again."
    exit 1
fi

# Check Docker is running
if ! docker info &> /dev/null; then
    print_error "Docker is not running. Please start Docker and try again."
    exit 1
fi

print_success "All required tools are available."

# Set up Docker Buildx for multi-architecture builds
print_info "Setting up Docker Buildx for multi-architecture builds..."
BUILDER_NAME="plexmcp-builder"
if ! docker buildx inspect "$BUILDER_NAME" &> /dev/null 2>&1; then
    docker buildx create --name "$BUILDER_NAME" --driver docker-container --bootstrap > /dev/null 2>&1 || true
    print_success "Created buildx builder: $BUILDER_NAME"
else
    print_info "Buildx builder already exists: $BUILDER_NAME"
fi

# Directory setup
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
ENV_EXAMPLE="$PROJECT_ROOT/.env.example"

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    print_warning ".env file already exists."
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Keeping existing .env file."
        print_info "To regenerate secrets only, edit .env manually or delete it and run this script again."
        exit 0
    fi
fi

# Generate secure secrets
print_info "Generating secure secrets..."

JWT_SECRET=$(openssl rand -hex 32)
API_KEY_HMAC_SECRET=$(openssl rand -hex 32)
TOTP_ENCRYPTION_KEY=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)

print_success "Secrets generated successfully."

# Create .env file
print_info "Creating .env file..."

cat > "$ENV_FILE" << EOF
# PlexMCP Self-Hosted Configuration
# Generated by setup.sh on $(date)
#
# Documentation: https://docs.plexmcp.com/self-hosting/configuration

#############################################
# DATABASE
#############################################

# PostgreSQL connection string
DATABASE_URL=postgresql://plexmcp:${POSTGRES_PASSWORD}@localhost:5432/plexmcp

# Password for PostgreSQL (used by docker-compose)
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

#############################################
# REDIS
#############################################

REDIS_URL=redis://localhost:6379

#############################################
# SERVER
#############################################

# Server bind address
BIND_ADDRESS=0.0.0.0:8080

# Public-facing URL of your API
PUBLIC_URL=http://localhost:8080

# Base domain for multi-tenant routing (optional)
BASE_DOMAIN=localhost

#############################################
# AUTHENTICATION (DO NOT SHARE THESE!)
#############################################

# JWT signing secret (32+ bytes, randomly generated)
JWT_SECRET=${JWT_SECRET}

# JWT token expiry in hours
JWT_EXPIRY_HOURS=24

# API key HMAC secret (32+ bytes, randomly generated)
API_KEY_HMAC_SECRET=${API_KEY_HMAC_SECRET}

# 2FA TOTP encryption key (64 hex characters = 32 bytes)
TOTP_ENCRYPTION_KEY=${TOTP_ENCRYPTION_KEY}

#############################################
# SELF-HOSTED MODE
#############################################

# Enable self-hosted mode (disables cloud features)
PLEXMCP_SELF_HOSTED=true

# Disable billing (no Stripe integration)
ENABLE_BILLING=false

# Enable user signup
ENABLE_SIGNUP=true

# Disable email routing (no Resend integration)
ENABLE_EMAIL_ROUTING=false

#############################################
# MCP SETTINGS
#############################################

# MCP request timeout in milliseconds
MCP_REQUEST_TIMEOUT_MS=30000

# Maximum MCP connections per organization
MCP_MAX_CONNECTIONS_PER_ORG=100

#############################################
# LOGGING
#############################################

RUST_LOG=info,plexmcp=debug

#############################################
# OPTIONAL: SUPABASE (for OAuth)
#############################################
# Uncomment and fill in if you want OAuth (Google, GitHub, etc.)
# Otherwise, only email/password authentication will work.

# SUPABASE_URL=https://your-project.supabase.co
# SUPABASE_ANON_KEY=your-anon-key
# SUPABASE_SERVICE_ROLE_KEY=your-service-role-key
# SUPABASE_JWT_SECRET=your-jwt-secret

#############################################
# OPTIONAL: EMAIL (for transactional emails)
#############################################
# Uncomment and fill in to enable email sending
# Without this, features requiring email (password reset, etc.) won't work

# RESEND_API_KEY=re_your_api_key
# EMAIL_FROM=PlexMCP <noreply@yourdomain.com>
EOF

print_success ".env file created at: $ENV_FILE"

# Summary
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete!                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
print_info "Next steps:"
echo ""
echo "  1. Start the services (using pre-built images - recommended):"
echo "     ${GREEN}docker compose --profile prebuilt up -d${NC}"
echo ""
echo "     Or build from source:"
echo "     ${GREEN}docker compose --profile build up -d${NC}"
echo ""
echo "  2. Wait for services to be healthy:"
echo "     ${GREEN}docker compose ps${NC}"
echo "     ${GREEN}./scripts/health-check.sh${NC}"
echo ""
echo "  3. Open the application:"
echo "     ${GREEN}http://localhost:3000${NC}"
echo ""
echo "  4. Create your first account and start using PlexMCP!"
echo ""
print_warning "Security reminder:"
echo "  - Keep your .env file secret!"
echo "  - Never commit it to version control"
echo "  - Rotate secrets periodically"
echo ""
print_info "Documentation: https://docs.plexmcp.com/self-hosting"
print_info "Support: https://github.com/PlexMCP/plexmcp/discussions"
echo ""
